### PR TITLE
Task-22 in spanish

### PR DESCRIPTION
**Pull request by manlug**

### CODE REVIEW

**Comment by RodionGork** [comment]
Hi there!

I'm afraid something is wrong with your branch, it shows changes in 5 files, but most of them look like english copies. 

If you won't mind, I'll copy the file for `task-22` manually, as the PR have conflicts and couldn't be merged by github.

**Comment by RodionGork** [comment]
Hm... supposedly I should take also task-23, right?

Thanks for your efforts anyway :)

Probably you should synchronize your copy (or recreate your fork if it's easier) to avoid discrepancies between branches.

**Comment by manlug** [comment]
> Probably you should synchronize your copy (or recreate your fork if it's easier) to avoid discrepancies between branches.

ok

**Comment by RodionGork** [comment]
Nevertheless tasks 22 and 23 are added to site (you can check them). I put link to your github page in a commentary before text, so we can remember who is the author of translation :)

**Pull request closed without merging**
